-- Marketing-only website manager schema.
-- Do not store patient, appointment, billing, intake, or medical-record data here.

create table if not exists public.site_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.site_content (
  id text primary key,
  content jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  constraint site_content_main_row check (id = 'main')
);

create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  quote text not null check (char_length(quote) between 10 and 500),
  display_name text not null check (char_length(display_name) between 1 and 80),
  source text not null default 'Website testimonial',
  permission_confirmed boolean not null default false,
  published boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint published_testimonial_requires_permission check (not published or permission_confirmed)
);

create index if not exists site_content_updated_by_idx
on public.site_content (updated_by);

alter table public.site_admins enable row level security;
alter table public.site_content enable row level security;
alter table public.testimonials enable row level security;

grant usage on schema public to anon, authenticated;
revoke all on table public.site_admins from anon, authenticated;
revoke all on table public.site_content from anon, authenticated;
revoke all on table public.testimonials from anon, authenticated;
revoke all on sequence public.testimonials_id_seq from anon, authenticated;

grant select on public.site_admins to authenticated;
grant select on public.site_content to anon, authenticated;
grant update on public.site_content to authenticated;
grant select on public.testimonials to anon, authenticated;
grant insert, update, delete on public.testimonials to authenticated;
grant usage, select on sequence public.testimonials_id_seq to authenticated;

create policy "Site admins can view their own membership" on public.site_admins
for select to authenticated using ((select auth.uid()) = user_id);

create policy "Public can read website content" on public.site_content
for select to anon, authenticated using (true);

create policy "Site admins can update website content" on public.site_content
for update to authenticated
using (exists (select 1 from public.site_admins where site_admins.user_id = (select auth.uid())))
with check (id = 'main' and exists (select 1 from public.site_admins where site_admins.user_id = (select auth.uid())));

create policy "Visitors can read approved testimonials" on public.testimonials
for select to anon
using (published = true and permission_confirmed = true);

create policy "Signed-in users can read allowed testimonials" on public.testimonials
for select to authenticated
using (
  (published = true and permission_confirmed = true)
  or exists (
    select 1 from public.site_admins
    where site_admins.user_id = (select auth.uid())
  )
);

create policy "Site admins can add testimonials" on public.testimonials
for insert to authenticated
with check (exists (select 1 from public.site_admins where site_admins.user_id = (select auth.uid())));

create policy "Site admins can update testimonials" on public.testimonials
for update to authenticated
using (exists (select 1 from public.site_admins where site_admins.user_id = (select auth.uid())))
with check (exists (select 1 from public.site_admins where site_admins.user_id = (select auth.uid())));

create policy "Site admins can delete testimonials" on public.testimonials
for delete to authenticated
using (exists (select 1 from public.site_admins where site_admins.user_id = (select auth.uid())));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('marketing-images', 'marketing-images', true, 5242880, array['image/jpeg', 'image/png', 'image/webp']::text[])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "Site admins can list marketing images" on storage.objects
for select to authenticated
using (bucket_id = 'marketing-images' and exists (select 1 from public.site_admins where site_admins.user_id = (select auth.uid())));

create policy "Site admins can upload marketing images" on storage.objects
for insert to authenticated
with check (bucket_id = 'marketing-images' and exists (select 1 from public.site_admins where site_admins.user_id = (select auth.uid())));

create policy "Site admins can replace marketing images" on storage.objects
for update to authenticated
using (bucket_id = 'marketing-images' and exists (select 1 from public.site_admins where site_admins.user_id = (select auth.uid())))
with check (bucket_id = 'marketing-images' and exists (select 1 from public.site_admins where site_admins.user_id = (select auth.uid())));

create policy "Site admins can delete marketing images" on storage.objects
for delete to authenticated
using (bucket_id = 'marketing-images' and exists (select 1 from public.site_admins where site_admins.user_id = (select auth.uid())));

-- Harden the pre-existing profile setup used when Auth creates a user.
-- The function uses fully qualified object names and cannot be called directly
-- by website visitors or signed-in users.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$;

revoke execute on function public.handle_new_user() from public, anon, authenticated;
grant execute on function public.handle_new_user() to service_role;

drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile" on public.profiles
for select to authenticated
using ((select auth.uid()) = id);

-- Public before-and-after gallery. Patient names, initials, medical record
-- numbers, dates of birth, diagnoses, release documents, and medical notes do
-- not belong in this table.
create table if not exists public.gallery_items (
  id uuid primary key default gen_random_uuid(),
  case_number bigint generated always as identity unique,
  service text not null check (
    service in (
      'Botox & Neurotoxins',
      'Dermal Fillers',
      'Skin Treatments',
      'Wellness Progress',
      'Other Treatment'
    )
  ),
  before_url text not null check (char_length(before_url) between 10 and 2000),
  after_url text not null check (char_length(after_url) between 10 and 2000),
  before_path text not null check (char_length(before_path) between 5 and 500),
  after_path text not null check (char_length(after_path) between 5 and 500),
  authorization_confirmed boolean not null default false,
  privacy_checked boolean not null default false,
  authorization_verified_at timestamptz,
  authorization_verified_by uuid references auth.users(id) on delete restrict,
  published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint gallery_requires_authorization_before_storage check (
    authorization_confirmed = true
    and privacy_checked = true
    and authorization_verified_at is not null
    and authorization_verified_by is not null
  ),
  constraint published_gallery_requires_authorization check (
    not published
    or (
      authorization_confirmed = true
      and privacy_checked = true
      and authorization_verified_at is not null
      and authorization_verified_by is not null
    )
  )
);

create index if not exists gallery_items_public_order_idx
on public.gallery_items (sort_order, case_number desc)
where published = true and authorization_confirmed = true and privacy_checked = true;

create index if not exists gallery_items_authorization_verified_by_idx
on public.gallery_items (authorization_verified_by);

alter table public.gallery_items enable row level security;

revoke all on table public.gallery_items from anon, authenticated;
revoke all on sequence public.gallery_items_case_number_seq from anon, authenticated;
grant select on public.gallery_items to anon, authenticated;
grant insert, update, delete on public.gallery_items to authenticated;
grant usage, select on sequence public.gallery_items_case_number_seq to authenticated;

create policy "Visitors can read approved gallery items" on public.gallery_items
for select to anon
using (published and authorization_confirmed and privacy_checked and authorization_verified_at is not null);

create policy "Signed-in users can read allowed gallery items" on public.gallery_items
for select to authenticated
using (
  (published and authorization_confirmed and privacy_checked and authorization_verified_at is not null)
  or exists (
    select 1 from public.site_admins
    where site_admins.user_id = (select auth.uid())
  )
);

create policy "Site admins can add gallery items" on public.gallery_items
for insert to authenticated
with check (
  authorization_confirmed
  and privacy_checked
  and authorization_verified_at is not null
  and authorization_verified_by = (select auth.uid())
  and exists (
    select 1 from public.site_admins
    where site_admins.user_id = (select auth.uid())
  )
);

create policy "Site admins can update gallery items" on public.gallery_items
for update to authenticated
using (
  exists (
    select 1 from public.site_admins
    where site_admins.user_id = (select auth.uid())
  )
)
with check (
  authorization_confirmed
  and privacy_checked
  and authorization_verified_at is not null
  and authorization_verified_by is not null
  and exists (
    select 1 from public.site_admins
    where site_admins.user_id = (select auth.uid())
  )
);

create policy "Site admins can delete gallery items" on public.gallery_items
for delete to authenticated
using (
  exists (
    select 1 from public.site_admins
    where site_admins.user_id = (select auth.uid())
  )
);
